[workspace]
channels = ["conda-forge"]
conda-pypi-map = {conda-forge = ".mapping.json"}
name = "codeaster-src"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
configure = {cmd = ["./configure"]}

build = {cmd = ["make"]}
install = {depends-on = ["build"]}
make = {cmd = "make"}

[dependencies]
# python
mpi4py = "4.0.*"
numpy = "1.24.*"
python = "3.11.*"
scipy = ">=1.15.2,<2"
# compilers
gcc = "14.*"
gfortran = "14.*"
gxx = "14.*"
mpi = "==1.0"
openmpi = ">=5.0.7,<6"
# mathematical libraries
blas = {version = "*", build = "openblas"}
scalapack = ">=2.2.0,<3"
# libs
hdf5 = ">=1.14,<2"
libmed = {version = "4.1.*", build = "mpi_openmpi*"}
libptscotch = ">7"
medcoupling = ">=9.12.0,<10"
metis = ">=5.1.0,<6"
mfront = "<5.0"
mgis = "<3.0"
mumps-mpi = ">5.4,<5.9"
parmetis = ">=4.0.3,<5"
petsc = ">3.17,<3.22"
petsc4py = ">=3.21.6,<4"
slepc = "*"
slepc4py = ">=3.21.2,<4"
zlib = ">=1.3.1,<2"
# optional packages
sympy = ">=1.14.0,<2"
# developer tools
black = ">=25.1.0,<26"
ccache = ">=4.11.2,<5"
clang-format = "17.*"
cmake = "<4"
ipython = ">=9.0.2,<10"
make = ">=4.4.1,<5"
pyyaml = ">=6.0.2,<7"
ruff = ">=0.11.1,<0.12"
sphinx = "<7"
# external tools
gmsh = ">=4.13.1,<5"
# debugging tools (excluded from a future 'prod' environment?)
debugpy = "*"
py-spy = ">=0.4.0,<0.5"

[feature.rtd.dependencies]
mpi4py = "4.0.*"
numpy = "<2"
python = "3.12.*"
sphinx = "<7"
sphinx-rtd-theme = "*"

[feature.rtd.tasks]
builddoc = {cmd = "python -m sphinx -T -b html -d ../build/mpidebug/doc/doctrees -D language=en . ", cwd = "doc"}

[feature.mkl.dependencies]
mkl = "*"

[feature.latest.dependencies]
# python
mpi4py = ">=4.1.0,<5"
numpy = "*"
python = "*"
scipy = ">=1.16.0,<2"
# mathematical libraries
blas = {version = "*", build = "openblas"}
scalapack = ">=2.2.0,<3"
# compilers
gcc = ">=15"
gfortran = ">=15"
gxx = ">=15"
mpi = "==1.0"
openmpi = ">=5.0.7,<6"
#libs
hdf5 = ">=1.14.3,<2"
libmed = {version = "4.1.*", build = "mpi_openmpi*"}
libptscotch = ">7"
medcoupling = ">=9.12.0"
# mgis 2 doesn't compile with gcc 15
# mfront 5 not available
mfront = "*"
mgis = "*"
mumps-mpi = ">=5.7.3,<6"
petsc = "<3.22"
petsc4py = "*"
slepc = "<3.22"
slepc4py = "*"
zlib = "*"
# developer tools
black = "*"
ccache = "*"
clang-format = "17.*"
ipython = "*"
make = "*"
pyyaml = "*"
ruff = "*"
sphinx = "<7"

[environments]
latest = {features = ["latest"], no-default-feature = true}
mkl = ["mkl"]
rtd = {features = ["rtd"], no-default-feature = true}
