variables:
  MINIO_URL: https://minio.retd.edf.fr
  MINIO_MC: ./mc --insecure
  ROOT_URL: https://$GITLAB_TOKEN_NAME:$GITLAB_TOKEN@gitlab.pleiade.edf.fr/codeaster
  PREREQ_VERSION: 20240327
  OSNAME: debian-12
  IMAGE_URL: ${DOCKER_NEXUS_URL}/codeaster-prerequisites:${PREREQ_VERSION}-${OSNAME}
  ASTER_BUILD: mpi
  # BUILDTYPE: ci, nightly, nightly-coverage, code-checking, docker
  BUILDTYPE: ci
  REFREV: ${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}
  GIT_SSL_NO_VERIFY: "true"
  NPROC_MAX: 12
  FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR: "true"
  PIXI_HOME: ${CI_PROJECT_DIR}/.pixi
  # WEEKLY_RUN should be set in scheduled pipeline
  WEEKLY_RUN: "unset"
  TZ: "Europe/Paris"

default:
  tags:
    - docker-executor

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_REF_NAME == "main" && $CI_PIPELINE_SOURCE == "schedule"
      variables:
        REFREV: main
    - if: $CI_PIPELINE_SOURCE == "web"
      variables:
        REFREV: main
    - if: $BUILDTYPE == "code-checking"
    - if: $BUILDTYPE == "docker"
    - if: $BUILDTYPE == "nightly-coverage"
      variables:
        ASTER_BUILD: debug

  auto_cancel:
    on_new_commit: interruptible

stages:
  - setup
  - build
  - test
  - code-checking

image:
  name: ${IMAGE_URL}

before_script:
  - echo "started at $(date), day '$(date +%u)', weekly run on day '${WEEKLY_RUN}'"
  - export PATH="${PIXI_HOME}/bin:${PATH}"

.prepare:
  interruptible: true
  stage: setup
  script:
    - .gitlabci/prepare.sh
  artifacts:
    paths:
      - devtools/*
      - data-src/*
      - .pixi/*
    expire_in: 6 hours
  rules:
    - if: $BUILDTYPE != "code-checking" && $BUILDTYPE != "docker"

.compile:
  interruptible: true
  stage: build
  script:
    - .gitlabci/compile.sh
  artifacts:
    when: always
    paths:
      - .lock*
      - build/*
      - install/*
    expire_in: 6 hours
  rules:
    - if: $BUILDTYPE != "code-checking" && $BUILDTYPE != "docker"

doc_html:
  interruptible: true
  stage: build
  needs: ["prepare", "compile"]
  script:
    - .gitlabci/doc_html.sh
  artifacts:
    paths:
      - install/share/doc/html/*
    expire_in: 3 days
  rules:
    - if: $CI_MERGE_REQUEST_IID

minimal_build:
  interruptible: true
  stage: test
  needs:
    - job: prepare
    - job: compile
      artifacts: false
    - job: check_source
      artifacts: false
  script:
    - .gitlabci/compile_minimal.sh
  rules:
    - if: $CI_MERGE_REQUEST_IID

check_source:
  interruptible: true
  stage: test
  needs: ["prepare", "compile"]
  script:
    - .gitlabci/check_source.sh
  artifacts:
    paths:
      - list_issues.txt
    expire_in: 3 days
  rules:
    - if: $CI_MERGE_REQUEST_IID

check_issues:
  interruptible: true
  stage: test
  needs: ["prepare", "check_source"]
  script:
    - .gitlabci/check_issues.sh
  rules:
    - if: $CI_MERGE_REQUEST_IID

minimal_test:
  interruptible: true
  stage: test
  needs: ["prepare", "compile"]
  script:
    - .gitlabci/test.sh
        -R "(asrun0|mumps02b|supv002|vocab0|zzzz509j)"
        --resutest=results_mini
  artifacts:
    when: always
    paths:
      - results_mini/run_testcases.xml
      - results_mini/Testing/Temporary/*
      - results_mini/*
    expire_in: 3 days
    reports:
      junit: results_mini/run_testcases.xml
  rules:
    - if: $CI_MERGE_REQUEST_IID

.verification_test:
  interruptible: true
  stage: test
  tags:
    - hulk
  script:
    - .gitlabci/test.sh
        -L verification
        --exclude-testlist .gitlabci/known_failures-pleiade.list
        --resutest=results
  artifacts:
    when: always
    paths:
      - results/run_testcases.xml
      - results/Testing/Temporary/*
      - results/*
    expire_in: 3 days
    reports:
      junit: results/run_testcases.xml
  rules:
    - if: $BUILDTYPE != "code-checking" && $BUILDTYPE != "docker"

known_failures_test:
  interruptible: true
  stage: test
  needs:
    - job: prepare
    - job: compile
    - job: minimal_test
      artifacts: false
  script:
    - .gitlabci/test.sh
        --testlist .gitlabci/known_failures-pleiade.list
        --resutest=results_failures
  allow_failure: true
  artifacts:
    when: always
    paths:
      - results_failures/run_testcases.xml
      - results_failures/Testing/Temporary/*
      - results_failures/*
    expire_in: 3 days
    reports:
      junit: results_failures/run_testcases.xml
  rules:
    - if: $CI_MERGE_REQUEST_IID

sonarqube:
  interruptible: true
  stage: code-checking
  image:
    name: nexus.retd.edf.fr:5012/sonarsource/sonar-scanner-cli:latest
    entrypoint: ["/bin/sh", "-c"]
  script:
    - sonar-scanner
        -Dsonar.projectKey="gitlab-${CI_PROJECT_ID}"
        -Dsonar.projectName="${CI_PROJECT_PATH_SLUG}"
        -Dsonar.host.url="${SQ_SERVER}"
        -Dsonar.login="${SQ_TOKEN}"
        -Dsonar.projectBaseDir=.
        -Dsonar.sources=.
        -Dsonar.exclusions="data,extern,waf*,**/*.export,build/**,install/**"
        -Dsonar.python.file.suffixes=py,comm,com0,com1,com2
        -Dsonar.issue.ignore.multicriteria=f1
        -Dsonar.issue.ignore.multicriteria.f1.ruleKey=f90-rules:F90.DESIGN.Include
        -Dsonar.issue.ignore.multicriteria.f1.resourceKey="f90-rules:**/*.F90"
        -Dsonar.scanner.javaOpts="-Xmx2G -Xms512M -XX:+HeapDumpOnOutOfMemoryError"
  variables:
    SQ_SERVER: "https://sonar.pleiade.edf.fr:443"
  allow_failure: true
  rules:
    - if: $BUILDTYPE == "code-checking"

docker:
  stage: build
  image:
    name: nexus.retd.edf.fr/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - sh .gitlabci/build_docker_codeaster.sh ${OSNAME}
  allow_failure: true
  artifacts:
    paths:
      - artf/codeaster-main-*.dockerfile
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH && $BUILDTYPE == "nightly"
    - if: $BUILDTYPE == "docker"

# --- default build
prepare:
  extends: .prepare

compile:
  extends: .compile
  needs:
    - job: prepare

verification_test:
  extends: .verification_test
  needs:
    - job: prepare
    - job: compile
    - job: minimal_test
      artifacts: false
      optional: true
    - job: check_source
      artifacts: false
      optional: true
    - job: doc_html
      artifacts: false
      optional: true

# --- variant debian-next for nightly build: no image available
prepare_debian-next:
  variables:
    OSNAME: debian-13
  extends: .prepare
  rules:
    - when: manual
      allow_failure: true

compile_debian-next:
  variables:
    OSNAME: debian-13
  extends: .compile
  needs:
    - job: prepare_debian-next
      optional: true

verification_test_debian-next:
  variables:
    OSNAME: debian-13
  extends: .verification_test
  needs:
    - job: prepare_debian-next
      optional: true
    - job: compile_debian-next
      optional: true

# --- variant using code-aster-reqs package for nightly build / weekly testing
prepare_pkg:
  image:
    name: nexus.retd.edf.fr:5012/debian:bookworm
  variables:
    OSNAME: pkg
  extends: .prepare
  script:
    - apt-get update
    - apt-get install -y binutils curl git make patch
    - !reference [.prepare, script]
  rules:
    - if: $BUILDTYPE == "nightly"
      when: on_success
    - when: manual
      allow_failure: true

compile_pkg:
  image:
    name: nexus.retd.edf.fr:5012/debian:bookworm
  variables:
    OSNAME: pkg
    ASTER_REQS_CONFIRM: y
  extends: .compile
  needs:
    - job: prepare_pkg
      optional: true
  script:
    - apt-get update
    - apt-get install -y binutils curl git make patch
    - !reference [.compile, script]

verification_test_pkg:
  image:
    name: nexus.retd.edf.fr:5012/debian:bookworm
  variables:
    OSNAME: pkg
    OMPI_MCA_plm: ^rsh
  extends: .verification_test
  needs:
    - job: prepare_pkg
      optional: true
    - job: compile_pkg
      optional: true
  script:
    - test "$(date +%u)" -ne ${WEEKLY_RUN} && echo "not run" && exit 0
    - apt-get update
    - apt-get install -y cmake git wget
    - .gitlabci/add-allow-run-as-root.sh
    - !reference [.verification_test, script]
  allow_failure: true

# --- variant win for nightly build / weekly testing
prepare_win:
  variables:
    OSNAME: win
  extends: .prepare
  script:
    - !reference [.prepare, script]
  rules:
    - if: $BUILDTYPE == "nightly"
      when: on_success
    - when: manual
      allow_failure: true

compile_win:
  variables:
    OSNAME: win
  extends: .compile
  needs:
    - job: prepare_win
      optional: true
  script:
    - !reference [.compile, script]

verification_test_win:
  variables:
    OSNAME: win
  extends: .verification_test
  needs:
    - job: prepare_win
      optional: true
    - job: compile_win
      optional: true
  script:
    - test "$(date +%u)" -ne ${WEEKLY_RUN} && echo "not run" && exit 0
    - !reference [.verification_test, script]
  allow_failure: true

# --- variant using pixi for nightly build / weekly testing
prepare_pixi:
  image:
    name: nexus.retd.edf.fr:5075/debian-base:bookworm
  variables:
    OSNAME: pixi
  extends: .prepare
  script:
    - .gitlabci/prepare_pixi.sh
    - !reference [.prepare, script]
  rules:
    - if: $BUILDTYPE == "nightly"
      when: on_success
    - when: manual
      allow_failure: true

compile_pixi:
  image:
    name: nexus.retd.edf.fr:5075/debian-base:bookworm
  variables:
    OSNAME: pixi
  extends: .compile
  needs:
    - job: prepare_pixi
      optional: true
  script:
    - pixi list --explicit
    - ls -la ${PIXI_HOME} || true
    - pixi run .gitlabci/compile.sh

verification_test_pixi:
  image:
    name: nexus.retd.edf.fr:5075/debian-base:bookworm
  variables:
    OSNAME: pixi
  extends: .verification_test
  needs:
    - job: prepare_pixi
      optional: true
    - job: compile_pixi
      optional: true
  script:
    - test "$(date +%u)" -ne ${WEEKLY_RUN} && echo "not run" && exit 0
    - ls -la ${PIXI_HOME} || true
    - pixi run .gitlabci/test.sh
        -L verification
        --exclude-testlist .gitlabci/known_failures-pleiade.list
        --resutest=results
  allow_failure: true
