! --------------------------------------------------------------------
! Copyright (C) 1991 - 2025 - EDF R&D - www.code-aster.org
! This file is part of code_aster.
!
! code_aster is free software: you can redistribute it and/or modify
! it under the terms of the GNU General Public License as published by
! the Free Software Foundation, either version 3 of the License, or
! (at your option) any later version.
!
! code_aster is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU General Public License for more details.
!
! You should have received a copy of the GNU General Public License
! along with code_aster.  If not, see <http://www.gnu.org/licenses/>.
! --------------------------------------------------------------------
!
subroutine getRgiPara(nomres, nmatbe2)
!
! person_in_charge: etienne.grimal@edf.fr

    implicit none

    character(len=12), intent(out) :: nomres(*)
    integer(kind=8), intent(in) :: nmatbe2
!
    nomres(1) = 'HYDR'
    nomres(2) = 'HYDS'
    nomres(3) = 'RT'
    nomres(4) = 'REF'
    nomres(5) = 'RC'
    nomres(6) = 'DELT'
    nomres(7) = 'BETA'
    nomres(8) = 'EPT'
    nomres(9) = 'HRGI'
    nomres(10) = 'VVRG'
    nomres(11) = 'KGEL'
    nomres(12) = 'GFT'
    nomres(13) = 'EKFL'
    nomres(14) = 'YKSY'
    nomres(15) = 'XFLU'
    nomres(16) = 'TAUK'
    nomres(17) = 'TAUM'
    nomres(18) = 'NRJM'
    nomres(19) = 'DT80'
    nomres(20) = 'BSHR'
    nomres(21) = 'MSHR'
    nomres(22) = 'PORO'
    nomres(23) = 'VRAG'
    nomres(24) = 'NRJF'
    nomres(25) = 'SFLD'
    nomres(26) = 'MVGN'
    nomres(27) = 'EPC'
    nomres(28) = 'EKDC'
    nomres(29) = 'EKRG'
    nomres(30) = 'GFR'
    nomres(31) = 'ALAT'
    nomres(32) = 'KRGI'
    nomres(33) = 'TREF'
    nomres(34) = 'TSTH'
    nomres(35) = 'DFMX'
    nomres(36) = 'TAUG'
    nomres(37) = 'NRJG'
    nomres(38) = 'SRSG'
    nomres(39) = 'TRAG'
    nomres(40) = 'DIM3'
    nomres(41) = 'TDEF'
    nomres(42) = 'NRJP'
    nomres(43) = 'SRSD'
    nomres(44) = 'VDEF'
    nomres(45) = 'CNAD'
    nomres(46) = 'SSAD'
    nomres(47) = 'CNAK'
    nomres(48) = 'CNAB'
    nomres(49) = 'EXND'
    nomres(50) = 'EXMD'
    nomres(51) = 'TTDD'
    nomres(52) = 'TDID'
    nomres(53) = 'TFID'
    nomres(54) = 'NRJD'
    nomres(55) = 'TTRD'
    nomres(56) = 'TTKF'
    nomres(57) = 'HPEV'

    nomres(58) = 'YOUM'
    nomres(59) = 'NUM'

    nomres(nmatbe2+1) = 'NREN'

    nomres(nmatbe2+2) = 'ROA1'
    nomres(nmatbe2+3) = 'DEQ1'
    nomres(nmatbe2+4) = 'E1'
    nomres(nmatbe2+5) = 'SY1'
    nomres(nmatbe2+6) = 'TYR1'
    nomres(nmatbe2+7) = 'VR11'
    nomres(nmatbe2+8) = 'VR12'
    nomres(nmatbe2+9) = 'VR13'
    nomres(nmatbe2+10) = 'D_SIGM_EPSI1'
    nomres(nmatbe2+11) = 'TAUM1'
    nomres(nmatbe2+12) = 'EKR1'
    nomres(nmatbe2+13) = 'SKR1'
    nomres(nmatbe2+14) = 'ATR1'
    nomres(nmatbe2+15) = 'CTM1'
    nomres(nmatbe2+16) = 'XFL1'
    nomres(nmatbe2+17) = 'PRE1'
    nomres(nmatbe2+18) = 'TTR1'
    nomres(nmatbe2+19) = 'XNR1'
    nomres(nmatbe2+20) = 'MUS1'
    nomres(nmatbe2+21) = 'TAUK1'
    nomres(nmatbe2+22) = 'YKY1'

    nomres(nmatbe2+23) = 'ROA2'
    nomres(nmatbe2+24) = 'DEQ2'
    nomres(nmatbe2+25) = 'E2'
    nomres(nmatbe2+26) = 'SY2'
    nomres(nmatbe2+27) = 'TYR2'
    nomres(nmatbe2+28) = 'VR21'
    nomres(nmatbe2+29) = 'VR22'
    nomres(nmatbe2+30) = 'VR23'
    nomres(nmatbe2+31) = 'D_SIGM_EPSI2'
    nomres(nmatbe2+32) = 'TAUM2'
    nomres(nmatbe2+33) = 'EKR2'
    nomres(nmatbe2+34) = 'SKR2'
    nomres(nmatbe2+35) = 'ATR2'
    nomres(nmatbe2+36) = 'CTM2'
    nomres(nmatbe2+37) = 'XFL2'
    nomres(nmatbe2+38) = 'PRE2'
    nomres(nmatbe2+39) = 'TTR2'
    nomres(nmatbe2+40) = 'XNR2'
    nomres(nmatbe2+41) = 'MUS2'
    nomres(nmatbe2+42) = 'TAUK2'
    nomres(nmatbe2+43) = 'YKY2'

    nomres(nmatbe2+44) = 'ROA3'
    nomres(nmatbe2+45) = 'DEQ3'
    nomres(nmatbe2+46) = 'E3'
    nomres(nmatbe2+47) = 'SY3'
    nomres(nmatbe2+48) = 'TYR3'
    nomres(nmatbe2+49) = 'VR31'
    nomres(nmatbe2+50) = 'VR32'
    nomres(nmatbe2+51) = 'VR33'
    nomres(nmatbe2+52) = 'D_SIGM_EPSI3'
    nomres(nmatbe2+53) = 'TAUM3'

    nomres(nmatbe2+54) = 'EKR3'
    nomres(nmatbe2+55) = 'SKR3'
    nomres(nmatbe2+56) = 'ATR3'
    nomres(nmatbe2+57) = 'CTM3'
    nomres(nmatbe2+58) = 'XFL3'
    nomres(nmatbe2+59) = 'PRE3'
    nomres(nmatbe2+60) = 'TTR3'
    nomres(nmatbe2+61) = 'XNR3'
    nomres(nmatbe2+62) = 'MUS3'
    nomres(nmatbe2+63) = 'TAUK3'
    nomres(nmatbe2+64) = 'YKY3'

    nomres(nmatbe2+65) = 'ROA4'
    nomres(nmatbe2+66) = 'DEQ4'
    nomres(nmatbe2+67) = 'E4'
    nomres(nmatbe2+68) = 'SY4'
    nomres(nmatbe2+69) = 'TYR4'
    nomres(nmatbe2+70) = 'VR41'
    nomres(nmatbe2+71) = 'VR42'
    nomres(nmatbe2+72) = 'VR43'
    nomres(nmatbe2+73) = 'D_SIGM_EPSI4'
    nomres(nmatbe2+74) = 'TAUM4'
    nomres(nmatbe2+75) = 'EKR4'
    nomres(nmatbe2+76) = 'SKR4'
    nomres(nmatbe2+77) = 'ATR4'
    nomres(nmatbe2+78) = 'CTM4'
    nomres(nmatbe2+79) = 'XFL4'
    nomres(nmatbe2+80) = 'PRE4'
    nomres(nmatbe2+81) = 'TTR4'
    nomres(nmatbe2+82) = 'XNR4'
    nomres(nmatbe2+83) = 'MUS4'
    nomres(nmatbe2+84) = 'TAUK4'
    nomres(nmatbe2+85) = 'YKY4'

    nomres(nmatbe2+86) = 'ROA5'
    nomres(nmatbe2+87) = 'DEQ5'
    nomres(nmatbe2+88) = 'E5'
    nomres(nmatbe2+89) = 'SY5'
    nomres(nmatbe2+90) = 'TYR5'
    nomres(nmatbe2+91) = 'VR51'
    nomres(nmatbe2+92) = 'VR52'
    nomres(nmatbe2+93) = 'VR53'
    nomres(nmatbe2+94) = 'D_SIGM_EPSI5'
    nomres(nmatbe2+95) = 'TAUM5'
    nomres(nmatbe2+96) = 'EKR5'
    nomres(nmatbe2+97) = 'SKR5'
    nomres(nmatbe2+98) = 'ATR5'
    nomres(nmatbe2+99) = 'CTM5'
    nomres(nmatbe2+100) = 'XFL5'
    nomres(nmatbe2+101) = 'PRE5'
    nomres(nmatbe2+102) = 'TTR5'
    nomres(nmatbe2+103) = 'XNR5'
    nomres(nmatbe2+104) = 'MUS5'
    nomres(nmatbe2+105) = 'TAUK5'
    nomres(nmatbe2+106) = 'YKY5'

end subroutine
